language: java
jdk:
- oraclejdk8
notifications:
  slack: integratieproject2:JhoQxoRUfWvTPc7y5JTq18FN
  email: false
deploy:
  provider: heroku
  app: shrouded-harbor-41030
  strategy: git
  api_key:
    secure: eh93TAO1SEy3DyCAQdt4341gfd0B3NLhqIg+Yeiz+KBWCOersCfOLc/UdVpHL0zolC8zSvCxzvYx51dKQTiUjZMI3ARdjJVdUZEO9Evfkg9lsWSwNQiM0mMaChJ6QLnZWx2OpRYrXf1QDC1Cg7xcD+FE3E2DasSJyy6LKuDPEwP5N2KPG6R56XoGlKwrzRvKpEWNxj1pYxfjTs/fWz4Ni723s8sEq29ZJjfRKI62j4pRAMZkG4AyYD+T60w8OKTGtjjOwKZGCERI26y44nQh84Rho2IzESflRpAvlgBvouRqpUzWIOCSe9w/6SDizx5VlS7BlqBs/WQG2kzXdBVyLOIsfBdQIgVeOK49VVftD3eg4YbzVc2Osb2CihA5Py7KXoE7OIixVhckUkR0EK7AOm2hwYUxlj8Kan4rjceEqRErc2U/gkXJSvrjgKaSYqZDq0P4j/xxzVox3G5p/kNhSduTAYkv49YM1E78mPlZuvjI9kSp80LpwV/ZCf6GcbSzfK6P87cftJMcDo6cOuJbqXfaSqsmK5oSgT+B8eErIrf7lSwaFC+04kIOfXuccv5QdAnpadItJk6BQ8tIz0i2Jo66muGFTq13sTwrgCEBvlZrfWjRFeUZOO48zQWnKUnpdWI1s6R49oKFVz5OVp1ZghVHms5T/LupkkBqRaipUeg=
