spring:
    main:
        banner-mode: "off"
    jpa:
        hibernate:
            ddl-auto: create-drop
    mail:
        host: smtp.gmail.com
        username: kdo.team.h@gmail.com
        password: Kdoteamh
        properties:
            mail:
                smtp:
                    auth: true
                    socketFactory:
                        port: 465
                        class: javax.net.ssl.SSLSocketFactory
                        fallback: false
                    ssl:
                        enable: true

---

spring:
    profiles: travis

logging:
    level:
        root: WARN
        org:
            hibernate: OFF

---

spring:
    profiles: production
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        hibernate:
            ddl-auto: update
    datasource:
        url: ${JDBC_DATABASE_URL}
        driverClassName: org.postgresql.Driver
        removeAbandoned: true
        initialize: false
        initialSize: 5
        maxActive: 10
        maxIdle: 5
        minIdle: 2
