spring:
  jpa:
      hibernate:
        ddl-auto: create-drop

---

spring:
  profiles: production
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-79-125-117-94.eu-west-1.compute.amazonaws.com:5432/dakjepaet1m99c?user=cfmcvduwxtnlos&password=gcSuPsa-JVf9KXewQjuAxtESiU
    username: cfmcvduwxtnlos
    password: gcSuPsa-JVf9KXewQjuAxtESiU
