spring:
    main:
        banner-mode: "off"
    jpa:
        show-sql: false


---

spring:
    profiles: travis

logging:
    level:
        root: WARN
        org:
            hibernate: OFF
---

spring:
    profiles: production
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        show-sql: false
        hibernate:
            ddl-auto: create
    datasource:
        url: ${JDBC_DATABASE_URL}
        driverClassName: org.postgresql.Driver
        removeAbandoned: true
        initialSize: 5
        maxActive: 10
        maxIdle: 5
        minIdle: 2
